<?php

/**
 * @file
 * Hook implementations for the Changelogify module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\user\UserInterface;


/**
 * Implements hook_entity_insert().
 */
#[LegacyHook]
function changelogify_entity_insert(EntityInterface $entity): void {
  \Drupal::service('Drupal\changelogify\Hook\ChangelogifyHooks')->entityInsert($entity);
}

/**
 * Implements hook_entity_update().
 */
#[LegacyHook]
function changelogify_entity_update(EntityInterface $entity): void {
  \Drupal::service('Drupal\changelogify\Hook\ChangelogifyHooks')->entityUpdate($entity);
}

/**
 * Implements hook_entity_delete().
 */
#[LegacyHook]
function changelogify_entity_delete(EntityInterface $entity): void {
  \Drupal::service('Drupal\changelogify\Hook\ChangelogifyHooks')->entityDelete($entity);
}

/**
 * Implements hook_modules_installed().
 */
#[LegacyHook]
function changelogify_modules_installed(array $modules, bool $is_syncing): void {
  \Drupal::service('Drupal\changelogify\Hook\ChangelogifyHooks')->modulesInstalled($modules, $is_syncing);
}

/**
 * Implements hook_modules_uninstalled().
 */
#[LegacyHook]
function changelogify_modules_uninstalled(array $modules, bool $is_syncing): void {
  \Drupal::service('Drupal\changelogify\Hook\ChangelogifyHooks')->modulesUninstalled($modules, $is_syncing);
}

/**
 * Implements hook_user_insert().
 */
#[LegacyHook]
function changelogify_user_insert(UserInterface $account): void {
  \Drupal::service('Drupal\changelogify\Hook\ChangelogifyHooks')->userInsert($account);
}

/**
 * Implements hook_user_update().
 */
#[LegacyHook]
function changelogify_user_update(UserInterface $account): void {
  \Drupal::service('Drupal\changelogify\Hook\ChangelogifyHooks')->userUpdate($account);
}

/**
 * Implements hook_theme().
 */
#[LegacyHook]
function changelogify_theme($existing, $type, $theme, $path): array {
  return \Drupal::service('Drupal\changelogify\Hook\ChangelogifyHooks')->theme();
}
